module.exports = {
  projects: [
    '<rootDir>/apps/bookstore',
    '<rootDir>/libs/books/feature',
    '<rootDir>/libs/ui',
    '<rootDir>/libs/books/data-access',
    '<rootDir>/libs/books/ui',
    '<rootDir>/apps/api',
    '<rootDir>/libs/models',
    '<rootDir>/libs/genres/data-access',
    '<rootDir>/libs/utils',
    '<rootDir>/apps/health-client',
    '<rootDir>/libs/health/data-access',
    '<rootDir>/libs/health/feature',
    '<rootDir>/libs/patients/feature',
    '<rootDir>/libs/ailments/feature',
    '<rootDir>/libs/medications/feature',
    '<rootDir>/libs/models-health-client',
    '<rootDir>/libs/health-client/patients/ui',
    '<rootDir>/libs/health-client/medications/ui',
    '<rootDir>/libs/health-client/ailments/ui',
    '<rootDir>/libs/health-client/patients/data-access',
  ],
};
